# Generated by Django 4.0.1 on 2022-08-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('BG', 'Beginner'), ('IM', 'Intermediate'), ('PR', 'Pro')], default='', max_length=2, null=True),
        ),
    ]
