# Generated by Django 4.0.1 on 2022-08-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('NN', ''), ('BG', 'Beginner'), ('IM', 'Intermediate'), ('PR', 'Pro')], default='', max_length=2, null=True),
        ),
    ]
