# Generated by Django 4.0.1 on 2022-08-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='level',
            field=models.CharField(choices=[('', 'NONE'), ('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('PRO', 'Pro')], default='', max_length=12, null=True),
        ),
    ]
